# lab04ex04 Generative AI based Bollinger Bands 
# Students MUST complete the following declaration and fill in your particulars below:
"""
I declare that the lab work here submitted is original
except for source material explicitly acknowledged,
and that the same or closely related material has not been
previously submitted for another course.
I also acknowledge that I am aware of University policy and
regulations on honesty in academic work, and of the disciplinary
guidelines and procedures applicable to breaches of such
policy and regulations, as contained in the website.

University Guideline on Academic Honesty:
https://www.cuhk.edu.hk/policy/academichonesty/

According to Adoption of AI Approach #2 announced by the
course teacher, I have used AI tools in completing 
specified part(s) of this work with prior permission from 
the course teacher.  Such AI usage has been properly 
referenced and related inputs such as prompts have been 
provided.  All else have been done by me, without the use 
of AI tools.

"""
#Student Name : Wong Cheuk Yin
#Student ID : 1155192671
#Class/Section : CSCI2040
#Date : 4/12/25
#I have used AI tools in this work : YES
#Details of AI tools usage :
"""
Q.1 What is the URL of the AI tool?
perplexity.ai
Q.2 What is the model name and version of the AI tool?
auto-chosen model
Q.3 Here is my prompt (in point form or in a paragraph):
the specifications stated in the lab pdf file.
Q.4 Did it work as expected? Give details.
yes, the graph generated by the code is exactly what the lab required. and looks like the sample output provided in the lab pdf file.
Q.5 Did you have any follow-up prompts/actions? If yes, give details.
i checked the code generated by the AI tool line by line to make sure it is correct and understand what each line does.
Q.6 What do you think of this usage experience?
very satisfying, the AI tool generated the code quickly and accurately based on the prompt provided.
"""

# Generate code with AI tools

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the CSV file into a DataFrame
data = pd.read_csv('HSBC2023.csv', parse_dates=['Date'])
data.set_index('Date', inplace=True)

# Calculate the 20-day Simple Moving Average (SMA)
data['SMA20'] = data['Close'].rolling(window=20).mean()

# Calculate the 20-day rolling standard deviation
data['STD20'] = data['Close'].rolling(window=20).std()

# Calculate Upper and Lower Bollinger Bands
data['UpperBand'] = data['SMA20'] + (2 * data['STD20'])
data['LowerBand'] = data['SMA20'] - (2 * data['STD20'])

# Plotting
plt.figure(figsize=(12, 6))
plt.plot(data.index, data['Close'], label='Close Price', color='blue')
plt.plot(data.index, data['SMA20'], label='20-day SMA', color='orange')
plt.plot(data.index, data['UpperBand'], label='Upper Bollinger Band', color='green')
plt.plot(data.index, data['LowerBand'], label='Lower Bollinger Band', color='red')
plt.fill_between(data.index, data['UpperBand'], data['LowerBand'], color='gray', alpha=0.1)

plt.title('HSBC 2023 Closing Prices with Bollinger Bands')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.show()


